
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Vikash9570/Data/raw/main/train_data.csv
  local_data_files: artifacts/data_ingestion/data.csv
  unzip_dir: artifacts/data_ingestion


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  tokenizer_name: google/pegasus-large
  

model_trainer:
  root_dir: artifacts/data_trainer
  data_path: artifacts/data_ingestion/data.csv
  model_ckpt: google/pegasus-large
  

model_evaluation: 
  model_path: artifacts/data_trainer/pegasus-large-model
  tokenizer_path: artifacts/data_trainer/tokenizer
   
